// This file will be generated by Payload CMS when you run:
// pnpm generate:types
//

// For now, these are placeholder types that match our collections
/* eslint-disable @typescript-eslint/no-explicit-any */

export interface User {
  id: string
  name: string
  email: string
  role: 'admin' | 'editor'
  createdAt: string
  updatedAt: string
}

export interface Media {
  id: string
  alt: string
  caption?: string
  url: string
  filename: string
  mimeType: string
  filesize: number
  width: number
  height: number
  sizes?: {
    thumbnail?: ImageSize
    card?: ImageSize
    feature?: ImageSize
    hero?: ImageSize
  }
  createdAt: string
  updatedAt: string
}

export interface ImageSize {
  url: string
  width: number
  height: number
  filename: string
}

export interface Category {
  id: string
  name: string
  slug: string
  description?: string
  icon?: string
  createdAt: string
  updatedAt: string
}

export interface Service {
  id: string
  title: string
  slug: string
  description: string
  content?: any // Lexical rich text
  category: string | Category
  icon?: string
  featuredImage?: string | Media
  price: number
  originalPrice?: number
  priceUnit?: 'hour' | 'day' | 'month' | 'project' | 'one-time'
  features?: { feature: string }[]
  order?: number
  status: 'draft' | 'published'
  featured?: boolean
  createdAt: string
  updatedAt: string
}

export interface Page {
  id: string
  title: string
  slug: string
  heroType?: 'simple' | 'image' | 'pattern'
  heroImage?: string | Media
  heroSubtitle?: string
  content?: any // Lexical rich text
  layout?: PageBlock[]
  seo?: {
    metaTitle?: string
    metaDescription?: string
    ogImage?: string | Media
  }
  status: 'draft' | 'published'
  createdAt: string
  updatedAt: string
}

export type PageBlock = ContentBlock | CTABlock | FeaturesBlock | StatsBlock | TeamBlock

export interface ContentBlock {
  blockType: 'content-block'
  content?: any
}

export interface CTABlock {
  blockType: 'cta-block'
  heading: string
  description?: string
  buttonText: string
  buttonLink: string
  style?: 'navy' | 'blue' | 'light'
}

export interface FeaturesBlock {
  blockType: 'features-block'
  heading?: string
  features?: {
    icon?: string
    title: string
    description?: string
  }[]
}

export interface StatsBlock {
  blockType: 'stats-block'
  stats?: {
    value: string
    label: string
  }[]
}

export interface TeamBlock {
  blockType: 'team-block'
  heading?: string
  members?: {
    name: string
    role: string
    image?: string | Media
    bio?: string
  }[]
}

// Globals
export interface SiteSettings {
  siteName?: string
  siteDescription?: string
  logo?: string | Media
  favicon?: string | Media
  email?: string
  phone?: string
  address?: string
  whatsapp?: string
  socialLinks?: {
    platform: 'facebook' | 'twitter' | 'linkedin' | 'instagram' | 'youtube'
    url: string
  }[]
  defaultMetaTitle?: string
  defaultMetaDescription?: string
  defaultOgImage?: string | Media
}

export interface Navigation {
  mainNav?: {
    label: string
    link: string
    type?: 'internal' | 'external'
    subItems?: {
      label: string
      link: string
    }[]
  }[]
  ctaButton?: {
    enabled?: boolean
    label?: string
    link?: string
  }
}

export interface Footer {
  aboutText?: string
  quickLinks?: {
    label: string
    link: string
  }[]
  offices?: {
    city: string
    address?: string
    phone?: string
  }[]
  copyrightText?: string
  bottomLinks?: {
    label: string
    link: string
  }[]
}
